name = "tg-premium-worker"
main = "src/index.js"
compatibility_date = "2024-12-01"

# Привязки создадим в панели Cloudflare:
# - KV с именем binding'а DB
# - secrets: BOT_TOKEN, JWT_SECRET
# - variable: FRONTEND_URL
